class ImageModel {
  final String name;
  final String profession;
  final String university;
  final String city;
  final String day;
  ImageModel( {
    required this.name,
    required this.profession,
    required this.university,
    required this.city,
    required this.day,
  });
}

List<ImageModel> imageModels = [
  ImageModel(name: "আবু সাইদ",
      profession: "শিক্ষার্থী",
      university: "বেগম রোকেয়া বিশ্ববিদ্যালয়",
      day: 'মৃত্যু : ১৬ জুলাই, ২০২৪',
      city: 'পীরগঞ্জ, রংপুর'),
  ImageModel(name: "ফয়সাল আহমেদ শান্ত",
      profession: "শিক্ষার্থী",
      university: "ওমরগণি এম.ই.এস. কলেজ",
      day: 'মৃত্যু : ১৬ জুলাই, ২০২৪',
      city: 'পতেঙ্গা, চট্টগ্রাম'),
  ImageModel(name: "মোঃ ওয়াসিম আকরুম",
    profession: "শিক্ষার্থী",
    university:"চট্টগ্রাম কলেজ, চট্টগ্রাম",
    city: " চট্টগ্রাম",
    day: "মৃত্যু : ১৬ জুলাই, ২০২৪"),
  ImageModel(name: "মোঃ ফারুক",
      profession: "চাকরিজীবী",
      university:"...",
      city: "কুমিল্লা",
      day: "মৃত্যু : ১৬ জুলাই, ২০২৪"),
  ImageModel(name: "সাকিব হাসান",
      profession: "শিক্ষার্থী",
      university:"আর,কে চোধূরী স্কুল এন্ড কলেজ, সায়েদাবাদ,",
      city: "যাত্রাবাড়ী, ঢাকা",
      day: "মৃত্যু : ১৭ জুলাই, ২০২৪"),
  ImageModel(name: "তাহমিদ তামিম",
      profession: "শিক্ষার্থী",
      university:"কাদির মোল্লা হাই স্কুল, নরসিংদী",
      city: "নরসিংদী",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "মীর মুগ্ধ",
      profession: "শিক্ষার্থী",
      university:"বাংলাদেশ ইউনিভার্সিটি অফ প্রফেশনালস",
      city: ".....",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "শাইখ আশহাবুল ইয়ামিন",
      profession: "শিক্ষার্থী",
      university:"মিলিটারি ইনস্টিটিউট অফ সায়েন্স অ্যান্ড",
      city: "কুমারখালী, কুষ্টিয়া, খুলনা",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "জাহিদ্দুজ্জামান তানভিন",
      profession: "শিক্ষার্থী",
      university:"ইসলামিক ইউনিভার্সিটি অফ টেকনোলজি, গাজীপুর",
      city: " ব্রাহ্মণবাড়িয়া, চট্টগ্রাম",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "ফারহান ফাইয়াজ",
      profession: "শিক্ষার্থী",
      university:"ঢাকা রেসিডেনসিয়াল মডেল কলেজ, মোহাম্মদপুর",
      city: "মোহাম্মদপুর",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "শাকিল পারভেজ",
      profession: "শিক্ষার্থী",
      university:"মানারাত ইন্টারন্যাশনাল ইউনিভার্সিটি",
      city: "গাজীপুর, ঢাকা",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "মৃত্যু তারিখ : ১৮ জুলাই, ২০২৪",
      profession: "শিক্ষার্থী",
      university:"ইম্পেরিয়াল কলেজ, ঢাকা",
      city: "গোপালগঞ্জ, ঢাকা",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "শেখ ফাহমিন জাফর",
      profession: "শিক্ষার্থী",
      university:"টংগী সরকারি কলেজ",
      city: "আত্রাই, নওগাঁ, রাজশাহী",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),
  ImageModel(name: "শাহ নেওয়াজ ফাহাদ",
      profession: "শিক্ষার্থী",
      university:"ইস্ট ওয়েস্ট ইউনিভার্সিটি, ঢাকা",
      city: "....",
      day: "মৃত্যু : ১৮ জুলাই, ২০২৪"),

];
